# Generated by Django 5.2.8 on 2025-12-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='hashed_password', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('rol', models.TextField()),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_queda_articulo', models.BooleanField(blank=True, null=True)),
                ('motivo_devolucion', models.TextField(blank=True, null=True)),
                ('valoracion', models.IntegerField(blank=True, null=True)),
                ('comentario_valoracion', models.TextField(blank=True, null=True)),
                ('fecha_valoracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coste_servicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_primer_pedido', models.BooleanField(blank=True, null=True)),
                ('total_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendations',
            fields=[
                ('pk', models.CompositePrimaryKey('product_id', 'recommended_product_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_recommendations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('seccion', models.CharField(max_length=100)),
                ('subseccion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.TextField(blank=True, null=True)),
                ('tags_ia', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StyleProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla_superior', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_inferior', models.CharField(blank=True, max_length=10, null=True)),
                ('estilo_preferido', models.CharField(blank=True, max_length=100, null=True)),
                ('presupuesto_rango', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gustos_texto', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'style_profiles',
                'managed': False,
            },
        ),
    ]
